name: .NET

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.13
        with:
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
  build:
    name: Build Release
    needs: create_release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Archive Release
      uses: thedoctor0/zip-release@main
      with:
        directory: ${{ github.workspace }}/ADTHeightDump/bin/Release/net7.0
        type: 'zip'
        filename: ${{ github.workspace }}/Release-${{ matrix.target }}.zip
    - name: Release
      uses: softprops/action-gh-release@v0.1.13
      with:
        files: ${{ github.workspace }}/Release-${{ matrix.target }}.zip